version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: billing_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: billing
      POSTGRES_PASSWORD: billing
      POSTGRES_DB: billing
    ports:
      - "5435:5432"
    volumes:
      - billing_postgres_data:/var/lib/postgresql/data

volumes:
  billing_postgres_data:
